Almoxarifado/Almoxarifado/grails-app/domain/almoxarifado/Alocacao.groovy
package almoxarifado

class Alocacao {
    Date data
    static hasMany = [permanente:Permanente, bensdeconsumo: BensDeConsumo]
    static constraints = {
    }
}

Almoxarifado/Almoxarifado/grails-app/controllers/almoxarifado/AlocacaoController.groovy
package almoxarifado



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import org.springframework.security.access.annotation.Secured
@Secured('isFullyAuthenticated()')

@Transactional(readOnly = true)
class AlocacaoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Alocacao.list(params), model:[alocacaoInstanceCount: Alocacao.count()]
    }

    def show(Alocacao alocacaoInstance) {
        respond alocacaoInstance
    }

    def create() {
        respond new Alocacao(params)
    }

    @Transactional
    def save(Alocacao alocacaoInstance) {
        if (alocacaoInstance == null) {
            notFound()
            return
        }

        if (alocacaoInstance.hasErrors()) {
            respond alocacaoInstance.errors, view:'create'
            return
        }

        alocacaoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'alocacao.label', default: 'Alocacao'), alocacaoInstance.id])
                redirect alocacaoInstance
            }
            '*' { respond alocacaoInstance, [status: CREATED] }
        }
    }

    def edit(Alocacao alocacaoInstance) {
        respond alocacaoInstance
    }

    @Transactional
    def update(Alocacao alocacaoInstance) {
        if (alocacaoInstance == null) {
            notFound()
            return
        }

        if (alocacaoInstance.hasErrors()) {
            respond alocacaoInstance.errors, view:'edit'
            return
        }

        alocacaoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Alocacao.label', default: 'Alocacao'), alocacaoInstance.id])
                redirect alocacaoInstance
            }
            '*'{ respond alocacaoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Alocacao alocacaoInstance) {

        if (alocacaoInstance == null) {
            notFound()
            return
        }

        alocacaoInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Alocacao.label', default: 'Alocacao'), alocacaoInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'alocacao.label', default: 'Alocacao'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Almoxarifado/Almoxarifado/grails-app/views/alocacao/_form.gsp
<%@ page import="almoxarifado.Alocacao" %>



<div class="fieldcontain ${hasErrors(bean: alocacaoInstance, field: 'bensdeconsumo', 'error')} ">
	<label for="bensdeconsumo">
		<g:message code="alocacao.bensdeconsumo.label" default="Bensdeconsumo" />
		
	</label>
	<g:select name="bensdeconsumo" from="${almoxarifado.BensDeConsumo.list()}" multiple="multiple" optionKey="id" size="5" value="${alocacaoInstance?.bensdeconsumo*.id}" class="many-to-many"/>

</div>

<div class="fieldcontain ${hasErrors(bean: alocacaoInstance, field: 'data', 'error')} required">
	<label for="data">
		<g:message code="alocacao.data.label" default="Data" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="data" precision="day"  value="${alocacaoInstance?.data}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: alocacaoInstance, field: 'permanente', 'error')} ">
	<label for="permanente">
		<g:message code="alocacao.permanente.label" default="Permanente" />
		
	</label>
	<g:select name="permanente" from="${almoxarifado.Permanente.list()}" multiple="multiple" optionKey="id" size="5" value="${alocacaoInstance?.permanente*.id}" class="many-to-many"/>

</div>

Almoxarifado/Almoxarifado/grails-app/views/alocacao/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'alocacao.label', default: 'Alocacao')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-alocacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-alocacao" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${alocacaoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${alocacaoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:alocacaoInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/alocacao/edit.gsp
<%@ page import="almoxarifado.Alocacao" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'alocacao.label', default: 'Alocacao')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-alocacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-alocacao" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${alocacaoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${alocacaoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:alocacaoInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${alocacaoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/alocacao/index.gsp
<%@ page import="almoxarifado.Alocacao" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'alocacao.label', default: 'Alocacao')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-alocacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-alocacao" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="data" title="${message(code: 'alocacao.data.label', default: 'Data')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${alocacaoInstanceList}" status="i" var="alocacaoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${alocacaoInstance.id}">${fieldValue(bean: alocacaoInstance, field: "data")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${alocacaoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/alocacao/show.gsp
<%@ page import="almoxarifado.Alocacao" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'alocacao.label', default: 'Alocacao')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-alocacao" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-alocacao" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list alocacao">
			
				<g:if test="${alocacaoInstance?.bensdeconsumo}">
				<li class="fieldcontain">
					<span id="bensdeconsumo-label" class="property-label"><g:message code="alocacao.bensdeconsumo.label" default="Bensdeconsumo" /></span>
					
						<g:each in="${alocacaoInstance.bensdeconsumo}" var="b">
						<span class="property-value" aria-labelledby="bensdeconsumo-label"><g:link controller="bensDeConsumo" action="show" id="${b.id}">${b?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${alocacaoInstance?.data}">
				<li class="fieldcontain">
					<span id="data-label" class="property-label"><g:message code="alocacao.data.label" default="Data" /></span>
					
						<span class="property-value" aria-labelledby="data-label"><g:formatDate date="${alocacaoInstance?.data}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${alocacaoInstance?.permanente}">
				<li class="fieldcontain">
					<span id="permanente-label" class="property-label"><g:message code="alocacao.permanente.label" default="Permanente" /></span>
					
						<g:each in="${alocacaoInstance.permanente}" var="p">
						<span class="property-value" aria-labelledby="permanente-label"><g:link controller="permanente" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:alocacaoInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${alocacaoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>