Almoxarifado/Almoxarifado/grails-app/domain/almoxarifado/Relatorio.groovy
package almoxarifado

class Relatorio {
    
    RegistroBP registrobp
    RegistroBC registrobc
    
    static constraints = {
    }
}

Almoxarifado/Almoxarifado/grails-app/controllers/almoxarifado/RelatorioController.groovy
package almoxarifado

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import org.springframework.security.access.annotation.Secured
@Secured('isFullyAuthenticated()')

@Transactional(readOnly = true)
class RelatorioController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Relatorio.list(params), model:[relatorioInstanceCount: Relatorio.count()]
    }

    def show(Relatorio relatorioInstance) {
        respond relatorioInstance
    }

    def create() {
        respond new Relatorio(params)
    }

    @Transactional
    def save(Relatorio relatorioInstance) {
        if (relatorioInstance == null) {
            notFound()
            return
        }

        if (relatorioInstance.hasErrors()) {
            respond relatorioInstance.errors, view:'create'
            return
        }

        relatorioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'relatorio.label', default: 'Relatorio'), relatorioInstance.id])
                redirect relatorioInstance
            }
            '*' { respond relatorioInstance, [status: CREATED] }
        }
    }

    def edit(Relatorio relatorioInstance) {
        respond relatorioInstance
    }

    @Transactional
    def update(Relatorio relatorioInstance) {
        if (relatorioInstance == null) {
            notFound()
            return
        }

        if (relatorioInstance.hasErrors()) {
            respond relatorioInstance.errors, view:'edit'
            return
        }

        relatorioInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Relatorio.label', default: 'Relatorio'), relatorioInstance.id])
                redirect relatorioInstance
            }
            '*'{ respond relatorioInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Relatorio relatorioInstance) {

        if (relatorioInstance == null) {
            notFound()
            return
        }

        relatorioInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Relatorio.label', default: 'Relatorio'), relatorioInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'relatorio.label', default: 'Relatorio'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Almoxarifado/Almoxarifado/grails-app/views/relatorio/_form.gsp
<%@ page import="almoxarifado.Relatorio" %>



<div class="fieldcontain ${hasErrors(bean: relatorioInstance, field: 'registrobc', 'error')} required">
	<label for="registrobc">
		<g:message code="relatorio.registrobc.label" default="Registrobc" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="registrobc" name="registrobc.id" from="${almoxarifado.RegistroBC.list()}" optionKey="id" required="" value="${relatorioInstance?.registrobc?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: relatorioInstance, field: 'registrobp', 'error')} required">
	<label for="registrobp">
		<g:message code="relatorio.registrobp.label" default="Registrobp" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="registrobp" name="registrobp.id" from="${almoxarifado.RegistroBP.list()}" optionKey="id" required="" value="${relatorioInstance?.registrobp?.id}" class="many-to-one"/>

</div>

Almoxarifado/Almoxarifado/grails-app/views/relatorio/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'relatorio.label', default: 'Relatorio')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-relatorio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-relatorio" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${relatorioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${relatorioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:relatorioInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/relatorio/edit.gsp
<%@ page import="almoxarifado.Relatorio" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'relatorio.label', default: 'Relatorio')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-relatorio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-relatorio" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${relatorioInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${relatorioInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:relatorioInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${relatorioInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/relatorio/index.gsp
<%@ page import="almoxarifado.Relatorio" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'relatorio.label', default: 'Relatorio')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-relatorio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-relatorio" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="relatorio.registrobc.label" default="Registrobc" /></th>
					
						<th><g:message code="relatorio.registrobp.label" default="Registrobp" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${relatorioInstanceList}" status="i" var="relatorioInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${relatorioInstance.id}">${fieldValue(bean: relatorioInstance, field: "registrobc")}</g:link></td>
					
						<td>${fieldValue(bean: relatorioInstance, field: "registrobp")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${relatorioInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/relatorio/show.gsp
<%@ page import="almoxarifado.Relatorio" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'relatorio.label', default: 'Relatorio')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-relatorio" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-relatorio" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list relatorio">
			
				<g:if test="${relatorioInstance?.registrobc}">
				<li class="fieldcontain">
					<span id="registrobc-label" class="property-label"><g:message code="relatorio.registrobc.label" default="Registrobc" /></span>
					
						<span class="property-value" aria-labelledby="registrobc-label"><g:link controller="registroBC" action="show" id="${relatorioInstance?.registrobc?.id}">${relatorioInstance?.registrobc?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${relatorioInstance?.registrobp}">
				<li class="fieldcontain">
					<span id="registrobp-label" class="property-label"><g:message code="relatorio.registrobp.label" default="Registrobp" /></span>
					
						<span class="property-value" aria-labelledby="registrobp-label"><g:link controller="registroBP" action="show" id="${relatorioInstance?.registrobp?.id}">${relatorioInstance?.registrobp?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:relatorioInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${relatorioInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>