Almoxarifado/Almoxarifado/grails-app/domain/almoxarifado/Locador.groovy
package almoxarifado

class Locador {
    
    String nome
    String rua
    String numero
    String bairro
    String sexo
    String email
    String telefone
    
    static constraints = {
        nome nullabel:false, blank: false, maxSize:35
        numero nullabel:false, blank: false, maxSize:35
        email email:true, unique:true
        sexo(inList:["Feminino", "Masculino"])
    }

       String toString(){
        nome
    }
}

Almoxarifado/Almoxarifado/grails-app/controllers/almoxarifado/LocadorController.groovy
package almoxarifado

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import org.springframework.security.access.annotation.Secured
@Secured('isFullyAuthenticated()')

@Transactional(readOnly = true)
class LocadorController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Locador.list(params), model:[locadorInstanceCount: Locador.count()]
    }

    def show(Locador locadorInstance) {
        respond locadorInstance
    }

    def create() {
        respond new Locador(params)
    }

    @Transactional
    def save(Locador locadorInstance) {
        if (locadorInstance == null) {
            notFound()
            return
        }

        if (locadorInstance.hasErrors()) {
            respond locadorInstance.errors, view:'create'
            return
        }

        locadorInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'locador.label', default: 'Locador'), locadorInstance.id])
                redirect locadorInstance
            }
            '*' { respond locadorInstance, [status: CREATED] }
        }
    }

    def edit(Locador locadorInstance) {
        respond locadorInstance
    }

    @Transactional
    def update(Locador locadorInstance) {
        if (locadorInstance == null) {
            notFound()
            return
        }

        if (locadorInstance.hasErrors()) {
            respond locadorInstance.errors, view:'edit'
            return
        }

        locadorInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Locador.label', default: 'Locador'), locadorInstance.id])
                redirect locadorInstance
            }
            '*'{ respond locadorInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Locador locadorInstance) {

        if (locadorInstance == null) {
            notFound()
            return
        }

        locadorInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Locador.label', default: 'Locador'), locadorInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'locador.label', default: 'Locador'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Almoxarifado/Almoxarifado/grails-app/views/locador/_form.gsp
<%@ page import="almoxarifado.Locador" %>



<div class="fieldcontain ${hasErrors(bean: locadorInstance, field: 'nome', 'error')} required">
	<label for="nome">
		<g:message code="locador.nome.label" default="Nome" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nome" maxlength="35" required="" value="${locadorInstance?.nome}"placeholder="Informe seu nome"/>

</div>

<div class="fieldcontain ${hasErrors(bean: locadorInstance, field: 'numero', 'error')} required">
	<label for="numero">
		<g:message code="locador.numero.label" default="Numero" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="numero" maxlength="35" required="" value="${locadorInstance?.numero}"placeholder="Informe o numero"/>

</div>

<div class="fieldcontain ${hasErrors(bean: locadorInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="locador.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="email" name="email" required="" value="${locadorInstance?.email}"placeholder="informe o email"/>

</div>

<div class="fieldcontain ${hasErrors(bean: locadorInstance, field: 'sexo', 'error')} required">
	<label for="sexo">
		<g:message code="locador.sexo.label" default="Sexo" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="sexo" from="${locadorInstance.constraints.sexo.inList}" required="" value="${locadorInstance?.sexo}" valueMessagePrefix="locador.sexo"/>

</div>

<div class="fieldcontain ${hasErrors(bean: locadorInstance, field: 'bairro', 'error')} required">
	<label for="bairro">
		<g:message code="locador.bairro.label" default="Bairro" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="bairro" required="" value="${locadorInstance?.bairro}"placeholder="Informe o bairro"/>

</div>

<div class="fieldcontain ${hasErrors(bean: locadorInstance, field: 'rua', 'error')} required">
	<label for="rua">
		<g:message code="locador.rua.label" default="Rua" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="rua" required="" value="${locadorInstance?.rua}"placeholder="Informe a rua"/>

</div>

<div class="fieldcontain ${hasErrors(bean: locadorInstance, field: 'telefone', 'error')} required">
	<label for="telefone">
		<g:message code="locador.telefone.label" default="Telefone" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="telefone" required="" value="${locadorInstance?.telefone}"placeholder="solicite seu telefone"/>

</div>

Almoxarifado/Almoxarifado/grails-app/views/locador/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'locador.label', default: 'Locador')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-locador" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-locador" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${locadorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${locadorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:locadorInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/locador/edit.gsp
<%@ page import="almoxarifado.Locador" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'locador.label', default: 'Locador')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-locador" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-locador" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${locadorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${locadorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:locadorInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${locadorInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/locador/index.gsp
<%@ page import="almoxarifado.Locador" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'locador.label', default: 'Locador')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-locador" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-locador" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nome" title="${message(code: 'locador.nome.label', default: 'Nome')}" />
					
						<g:sortableColumn property="numero" title="${message(code: 'locador.numero.label', default: 'Numero')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'locador.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="sexo" title="${message(code: 'locador.sexo.label', default: 'Sexo')}" />
					
						<g:sortableColumn property="bairro" title="${message(code: 'locador.bairro.label', default: 'Bairro')}" />
					
						<g:sortableColumn property="rua" title="${message(code: 'locador.rua.label', default: 'Rua')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${locadorInstanceList}" status="i" var="locadorInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${locadorInstance.id}">${fieldValue(bean: locadorInstance, field: "nome")}</g:link></td>
					
						<td>${fieldValue(bean: locadorInstance, field: "numero")}</td>
					
						<td>${fieldValue(bean: locadorInstance, field: "email")}</td>
					
						<td>${fieldValue(bean: locadorInstance, field: "sexo")}</td>
					
						<td>${fieldValue(bean: locadorInstance, field: "bairro")}</td>
					
						<td>${fieldValue(bean: locadorInstance, field: "rua")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${locadorInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Almoxarifado/Almoxarifado/grails-app/views/locador/show.gsp
<%@ page import="almoxarifado.Locador" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'locador.label', default: 'Locador')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-locador" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-locador" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list locador">
			
				<g:if test="${locadorInstance?.nome}">
				<li class="fieldcontain">
					<span id="nome-label" class="property-label"><g:message code="locador.nome.label" default="Nome" /></span>
					
						<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${locadorInstance}" field="nome"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${locadorInstance?.numero}">
				<li class="fieldcontain">
					<span id="numero-label" class="property-label"><g:message code="locador.numero.label" default="Numero" /></span>
					
						<span class="property-value" aria-labelledby="numero-label"><g:fieldValue bean="${locadorInstance}" field="numero"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${locadorInstance?.email}">
				<li class="fieldcontain">
					<span id="email-label" class="property-label"><g:message code="locador.email.label" default="Email" /></span>
					
						<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${locadorInstance}" field="email"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${locadorInstance?.sexo}">
				<li class="fieldcontain">
					<span id="sexo-label" class="property-label"><g:message code="locador.sexo.label" default="Sexo" /></span>
					
						<span class="property-value" aria-labelledby="sexo-label"><g:fieldValue bean="${locadorInstance}" field="sexo"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${locadorInstance?.bairro}">
				<li class="fieldcontain">
					<span id="bairro-label" class="property-label"><g:message code="locador.bairro.label" default="Bairro" /></span>
					
						<span class="property-value" aria-labelledby="bairro-label"><g:fieldValue bean="${locadorInstance}" field="bairro"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${locadorInstance?.rua}">
				<li class="fieldcontain">
					<span id="rua-label" class="property-label"><g:message code="locador.rua.label" default="Rua" /></span>
					
						<span class="property-value" aria-labelledby="rua-label"><g:fieldValue bean="${locadorInstance}" field="rua"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${locadorInstance?.telefone}">
				<li class="fieldcontain">
					<span id="telefone-label" class="property-label"><g:message code="locador.telefone.label" default="Telefone" /></span>
					
						<span class="property-value" aria-labelledby="telefone-label"><g:fieldValue bean="${locadorInstance}" field="telefone"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:locadorInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${locadorInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>